"""Updated the invitation status

Revision ID: 0a92cbbe3286
Revises: dd5a3b7975b3
Create Date: 2026-03-11 10:10:11.228492

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0a92cbbe3286"
down_revision: str | None = "dd5a3b7975b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute("ALTER TYPE invitationstatus ADD VALUE 'COMPLETED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
