"""Added interview transcript table

Revision ID: 2f738c91383e
Revises: 150985e50cb6
Create Date: 2026-02-26 12:53:39.318896

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f738c91383e'
down_revision: Union[str, None] = '150985e50cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_transcripts',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('full_transcript', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('transcript_gcs_url', sa.Text(), nullable=True),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.alter_column('assessments', 'job_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'job_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('interview_transcripts')
    # ### end Alembic commands ###