"""empty message

Revision ID: 402c4830a782
Revises: c1b1245d36b8
Create Date: 2026-02-24 15:48:42.773411

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "402c4830a782"
down_revision: str | None = "c1b1245d36b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
