"""add skill_graph column

Revision ID: 9bbeb0372a86
Revises: 2f738c91383e
Create Date: 2026-03-05 15:28:24.731212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bbeb0372a86'
down_revision: Union[str, None] = '2f738c91383e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resume_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='uq_candidates_org_email')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', postgresql.ENUM('SENT', 'CLICKED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invitation_id', sa.UUID(), nullable=True),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='interviewsessionstatus'), nullable=False),
    sa.Column('current_skill', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('refresh_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cultural_alignment_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('hiring_recommendation', postgresql.ENUM('STRONG_HIRE', 'HIRE', 'REJECT', name='hiringrecommendation'), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('admin_recommendation', postgresql.ENUM('STRONG_HIRE', 'HIRE', 'REJECT', name='hiringrecommendation'), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_tie_winner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('detailed_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.add_column('assessments', sa.Column('skill_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'interview_transcripts', 'interview_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_transcripts', type_='foreignkey')
    op.drop_column('assessments', 'skill_graph')
    op.drop_table('evaluations')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')

    op.drop_column("assessments", "skill_graph")
    # ### end Alembic commands ###