"""Created system log table

Revision ID: a8db742c87d8
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 22:00:31.674337

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8db742c87d8"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "evaluations",
        "is_tie_winner",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_foreign_key(
        None, "interview_transcripts", "interview_sessions", ["session_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "interview_transcripts", type_="foreignkey")
    op.alter_column(
        "evaluations",
        "is_tie_winner",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    # ### end Alembic commands ###
