"""add assessment table

Revision ID: bdcfb3f14994
Revises: 402c4830a782
Create Date: 2026-02-24 15:49:20.250734

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "bdcfb3f14994"
down_revision: str | None = "402c4830a782"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
