"""Updated the invitation status

Revision ID: dd5a3b7975b3
Revises: d98fa58add36
Create Date: 2026-03-11 10:07:54.102202

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dd5a3b7975b3"
down_revision: str | None = "d98fa58add36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE invitationstatus ADD VALUE 'COMPLETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
