"""create hiring and org tables

Revision ID: 3d0ca6c6d5da
Revises: b73144cecd29
Create Date: 2026-02-24 12:35:55.442492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0ca6c6d5da'
down_revision: Union[str, None] = 'b73144cecd29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###