"""add role column to hiring_managers

Revision ID: c1b1245d36b8
Revises: 3d0ca6c6d5da
Create Date: 2026-02-24 12:43:13.630745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b1245d36b8'
down_revision: Union[str, None] = '3d0ca6c6d5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_managers', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hiring_managers', 'role')
    # ### end Alembic commands ###