# name: Deploy Backend
# on:
#   push:
#     branches: [ main ]
# env:
#   PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
#   REGION: us-east1
#   REPOSITORY: keboli-repo

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}
#       - uses: google-github-actions/setup-gcloud@v2

#       - name: Get Agent URLs
#         run: |
#           # Fetch the URLs of the other services dynamically
#           INT_URL=$(gcloud run services describe interview-agent --platform managed --region $REGION --format='value(status.url)')
#           EVAL_URL=$(gcloud run services describe evaluation-agent --platform managed --region $REGION --format='value(status.url)')
#           echo "INTERVIEW_SERVICE_URL=$INT_URL" >> $GITHUB_ENV
#           echo "EVALUATION_SERVICE_URL=$EVAL_URL" >> $GITHUB_ENV

#       - name: Build and Push
#         run: |
#           gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
#           docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/backend:latest .
#           docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/backend:latest

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud run deploy keboli-backend \
#             --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/backend:latest \
#             --region $REGION \
#             --allow-unauthenticated \
#             --set-env-vars INTERVIEW_SERVICE_URL=${{ env.INTERVIEW_SERVICE_URL }},EVALUATION_SERVICE_URL=${{ env.EVALUATION_SERVICE_URL }}


on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/717740758627/locations/global/workloadIdentityPools/githubinterns/providers/github-provider
          service_account: gwx-gh-sa-01@gwx-internship-01.iam.gserviceaccount.com
          token_format: 'access_token'
      